### ISSUE TITLE
Not checking exonTree chromosomes

### ISSUE THREAD

**Issue by benbfly** [ababaian/LIONS#10]
This line seems to fail ungracefully in certain conditions:

LIONS/scripts/ChimericReadTool/chimericReadSearch.py line 109
`exon_results1 = exonTrees[str(chr)].findRange([start1,end1])`

I am running with a small number of reads, and this line errors because the read is from a chromosome with no exonTree entry. (because the chromosome doesn't exist in "assembly_exons" file)

Error below:
`Processing all reads
Traceback (most recent call last):
  File "/LIONS-docker/scripts/ChimericReadTool/chimericReadSearch.py", line 728, in <module>
    results = processReads(samfile_path, exonTrees, repeatTrees, chimericBedFile)
  File "/LIONS-docker/scripts/ChimericReadTool/chimericReadSearch.py", line 109, in processReads
    exon_results1 = exonTrees[str(chr)].findRange([start1,end1])
KeyError: '10'
read search complete.`

**Comment by ababaian** [comment]
I've ran into this once before and ungracefully used another reference genome with only the chromosome containing reads when I was running a pilot experiment. I then forgot about it, but I'll set this is a high priority and look to implement a proper work-around. I'm a little bit swamped at the moment but should get back to development fairly soon.

**Comment by biscuit13161** [comment]
@benbfly,

Can you confirm whether the suggested fix helped this issue? ..or does it need further work?

Thanks
Richard
