### ISSUE TITLE
chimericReadSearch.py: Error in Calculate Exon/Repeat Interactions

### ISSUE THREAD

**Issue by ababaian** [ababaian/LIONS#14]
Hey Richard (@biscuit13161)

I've been helping @dklinkebiel set up LIONS on a local system and ran into an error in the `chimericReadSearch.py` script. You're quite a bit better at python then me, would you mind trying to get to the bottom of this?

I've tracked the error down to occurring after Line 744, somewhere in the Exon/Repeat Interaction calculations.

[LIONS Error Output from Dave](https://github.com/dklinkebiel/LIONS-ERROR/files/3179214/LIONS_ERR.txt).

@dklinkebiel can you post the output of the following commands.

```
head -n 100 /lustre/work/epigenomics/klinkebiel/parallel/LIONS2/projects/sandbox/DKO_PreTumor/resources/assembly_exons_2

head -n 100 /lustre/work/epigenomics/klinkebiel/parallel/LIONS2/resources/mm10/repeat/forChimericSearch
```

**Comment by dklinkebiel** [comment]
Attached is the "First" <head -n 100 *> and "Second" request. This was a different run that had the same error so posting that error.
[Second.txt](https://github.com/ababaian/LIONS/files/3184448/Second.txt)
[First.txt](https://github.com/ababaian/LIONS/files/3184449/First.txt)
[LIONS_ERR.txt](https://github.com/ababaian/LIONS/files/3184450/LIONS_ERR.txt)

**Comment by biscuit13161** [comment]
Hi Dave,

Without having data, I'm having some issues figuring out exactly where the error is occurring.

Could you drop the attached file in place of the chimericReadSearch.py script you have (personally, I'd move the old one to keep it safe before saving this one without the .txt extension), rerun and send me the error log again.

Thanks,
Richard

[chimericReadSearch.py.txt](https://github.com/ababaian/LIONS/files/3196489/chimericReadSearch.py.txt)

**Comment by dklinkebiel** [comment]
Hi Richard,

Attached is the error log you requested. Thanks
[LIONS_ERR.txt](https://github.com/ababaian/LIONS/files/3203645/LIONS_ERR.txt)

Dave

**Comment by biscuit13161** [comment]
Apologies Dave,

I'm afraid introduced a typo in that file when I sent it previously. Could you try again with this attached file.

Thanks,
Richard

[chimericReadSearch.py.txt](https://github.com/ababaian/LIONS/files/3206523/chimericReadSearch.py.txt)

**Comment by dklinkebiel** [comment]
Here is the latest error log.

Dave
[LIONS_ERR.txt](https://github.com/ababaian/LIONS/files/3212527/LIONS_ERR.txt)

**Comment by dklinkebiel** [comment]
Hi Richard,

I was wondering if you got a chance to look at the LIONS error I was encountering. Thanks

David Klinkebiel

**Comment by biscuit13161** [comment]
Apologies Dave,

We had a national holiday here and I was caught up finishing things.

It looks like either it's happening after the output loop, which is the last thing in the script, or it's having an issue with a specific piece of data. However I can't see exactly were this error would arise...

Could you try running with this version of the script and let me have the error log again.

[chimericReadSearch.py.txt](https://github.com/ababaian/LIONS/files/3274840/chimericReadSearch.py.txt)

**Comment by dklinkebiel** [comment]
Here is the latest error log. Had to give dropbox link since file was to big to insert.

Dave

https://www.dropbox.com/s/89gmn5em2wyd585/LIONS_ERR.txt?dl=0

**Comment by biscuit13161** [comment]
Hi Dave,

Thanks, sorry I should have mentioned that I was expecting it to be a large file.
Could you send me the stdout log as well?

Thanks,
Richard

**Comment by dklinkebiel** [comment]
Here is the latest stdout log.

Dave
[LIONS_OUT.txt](https://github.com/ababaian/LIONS/files/3297286/LIONS_OUT.txt)

**Comment by biscuit13161** [comment]
hi Dave,

I suspect we've been looking in the wrong script. Could you revert the chimericReadSearch.py to its original from github and try using [chimGroup.R.txt](https://github.com/ababaian/LIONS/files/3300475/chimGroup.R.txt) in place of <LIONS_
Root>/scripts/ChimericAnalysis/chimGroup.R 
Please let me have both the error and stdout logs.

Thanks,
 Richard

**Comment by dklinkebiel** [comment]
Here is the latest error and stdout logs.

Dave
[LIONS_OUT.txt](https://github.com/ababaian/LIONS/files/3306376/LIONS_OUT.txt)
[LIONS_ERR.txt](https://github.com/ababaian/LIONS/files/3306377/LIONS_ERR.txt)

**Comment by biscuit13161** [comment]
Apologies Dave,

I thought I'd sent this to you last week...

as before can you try 
[chimGroup.R.txt](https://github.com/ababaian/LIONS/files/3333080/chimGroup.R.txt) and let me have the two log files.

Thanks,
Rich

**Comment by dklinkebiel** [comment]
Latest error and out logs. Thanks

Dave
[LIONS_ERR.txt](https://github.com/ababaian/LIONS/files/3340321/LIONS_ERR.txt)
[LIONS_OUT.txt](https://github.com/ababaian/LIONS/files/3340322/LIONS_OUT.txt)

**Comment by biscuit13161** [comment]
Hi Dave,

I think I understand what's happening but I'd appreciate it if you could run this file -
[chimGroup.R.txt](https://github.com/ababaian/LIONS/files/3342546/chimGroup.R.txt) - to confirm..

... Also would you mind including your input list file (.../parallel/LIONS/controls/input.list)

Thanks
Rich

**Comment by dklinkebiel** [comment]
Latest error and out logs and input.list

. Thanks

Dave
[LIONS_ERR.txt](https://github.com/ababaian/LIONS/files/3351338/LIONS_ERR.txt)
[LIONS_OUT.txt](https://github.com/ababaian/LIONS/files/3351339/LIONS_OUT.txt)
[input.list.txt](https://github.com/ababaian/LIONS/files/3351398/input.list.txt)

**Comment by biscuit13161** [comment]
Hi Dave,

Can you try again with this file - [chimGroup.R.txt](https://github.com/ababaian/LIONS/files/3357765/chimGroup.R.txt)

Thanks, Rich

**Comment by dklinkebiel** [comment]
Here is the latest error and out logs. Thanks

Dave
[LIONS_OUT.txt](https://github.com/ababaian/LIONS/files/3364767/LIONS_OUT.txt)
[LIONS_ERR.txt](https://github.com/ababaian/LIONS/files/3364768/LIONS_ERR.txt)

**Comment by biscuit13161** [comment]
Hi Dave,

Sorry, still investigating but can you try this [chimGroup.R.txt](https://github.com/ababaian/LIONS/files/3365298/chimGroup.R.txt)

Thanks,
Richard

**Comment by dklinkebiel** [comment]
Here is the latest error and out logs.
Dave
[LIONS_OUT.txt](https://github.com/ababaian/LIONS/files/3373894/LIONS_OUT.txt)
[LIONS_ERR.txt](https://github.com/ababaian/LIONS/files/3373895/LIONS_ERR.txt)

**Comment by biscuit13161** [comment]
Hi Dave,

Sorry about all the "To-ing and Fro-ing" but can you run this version ..
[chimGroup.R.txt](https://github.com/ababaian/LIONS/files/3376707/chimGroup.R.txt)

Thanks,
Richard

**Comment by dklinkebiel** [comment]
Here is the latest error and out logs. Thanks

Dave
[LIONS_OUT.txt](https://github.com/ababaian/LIONS/files/3382318/LIONS_OUT.txt)
[LIONS_ERR.txt](https://github.com/ababaian/LIONS/files/3382319/LIONS_ERR.txt)

**Comment by biscuit13161** [comment]
Hi Dave,

I'm sure this back and forth is annoying you as much as it is me ... is there anyway you could let me have an anonymised, minimum dataset that produces the same error? ... then I can do the testing myself

Thanks,
Richard

**Comment by dklinkebiel** [comment]
Here are links to the gzipped fastq files. I hope this works.
ftp://dklinkebiel@webmedia.unmc.edu/BIGDISK/htdocs/public/biochemistry/klinkebiel/GSF1734-D1-MT1_S7_R2_001_val_2.fq.gz
ftp://dklinkebiel@webmedia.unmc.edu/BIGDISK/htdocs/public/biochemistry/klinkebiel/GSF1734-D1-MT1_S7_R1_001_val_1.fq.gz
ftp://dklinkebiel@webmedia.unmc.edu/BIGDISK/htdocs/public/biochemistry/klinkebiel/GSF1734-D1-MT2_S8_R2_001_val_2.fq.gz
ftp://dklinkebiel@webmedia.unmc.edu/BIGDISK/htdocs/public/biochemistry/klinkebiel/GSF1734-D1-MT2_S8_R1_001_val_1.fq.gz
ftp://dklinkebiel@webmedia.unmc.edu/BIGDISK/htdocs/public/biochemistry/klinkebiel/GSF1734-D1-MT3_S9_R2_001_val_2.fq.gz
ftp://dklinkebiel@webmedia.unmc.edu/BIGDISK/htdocs/public/biochemistry/klinkebiel/GSF1734-D1-MT3_S9_R1_001_val_1.fq.gz
ftp://dklinkebiel@webmedia.unmc.edu/BIGDISK/htdocs/public/biochemistry/klinkebiel/GSF1734-D1-Ovid1_S1_R2_001_val_2.fq.gz
ftp://dklinkebiel@webmedia.unmc.edu/BIGDISK/htdocs/public/biochemistry/klinkebiel/GSF1734-D1-Ovid1_S1_R1_001_val_1.fq.gz
ftp://dklinkebiel@webmedia.unmc.edu/BIGDISK/htdocs/public/biochemistry/klinkebiel/GSF1734-D1-Ovid2_S2_R2_001_val_2.fq.gz
ftp://dklinkebiel@webmedia.unmc.edu/BIGDISK/htdocs/public/biochemistry/klinkebiel/GSF1734-D1-Ovid2_S2_R1_001_val_1.fq.gz
ftp://dklinkebiel@webmedia.unmc.edu/BIGDISK/htdocs/public/biochemistry/klinkebiel/GSF1734-D1-Ovid3_S3_R2_001_val_2.fq.gz
ftp://dklinkebiel@webmedia.unmc.edu/BIGDISK/htdocs/public/biochemistry/klinkebiel/GSF1734-D1-Ovid3_S3_R1_001_val_1.fq.gz

Dave

**Comment by biscuit13161** [comment]
Sorry Dave,

Those links don't seem to be working for me ... they keep timing out!

I can set up a shared Dropbox folder unless you have any other suggestions

Best,
Rich

**Comment by dklinkebiel** [comment]
Sure – set up a Dropbox folder. Thanks

Dave

**Comment by biscuit13161** [comment]
Dave

can you email me directly at "bawan03<at>gmail.com" so I can set up the shared Dropbox with the correct permissions?

Thanks,
Richard

**Comment by biscuit13161** [comment]
Hi Dave,

I think I've sorted it... It turns out that this issue occurred when the input.list contains non-unique library names. I've amended the code to allow for this, so if you can re-clone the git repository (I'm assuming you're not using the docker version) and let me know how it runs now.

Thanks,
Richard

**Comment by dklinkebiel** [comment]
Hi Richard,

I seem to be getting this message in my out log. Thanks

---------- Set-up Project Workspace ---------- 
 Initializing sandbox Directory: /lustre/work/epigenomics/klinkebiel/parallel/LIONS/projects/sandbox
/lustre/work/epigenomics/klinkebiel/parallel/LIONS/controls/input.list /lustre/work/epigenomics/klinkebiel/parallel/LIONS/controls/parameter.ctrl
 ERROR 7B: Input File Not Accesible (Fastq)
 files: /lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-Ovid1_S1_R1_001_val_1.fq ; /lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-Ovid1_S1_R2_001_val_2.fq
  a) The non-bam input file (.fq_1 & .fq_2) isnt found
  b) If youre using FASTQ; make sure youre listing two
     files in the input.list file seperated by a comma

Dave

**Comment by ababaian** [comment]
might the spaces between the semi colons?

**Comment by dklinkebiel** [comment]
This is my input.list

DKO_Ovid	/lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-Ovid1_S1_R1_001_val_1.fq,/lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-Ovid1_S1_R2_001_val_2.fq	1
DKO_Ovid	/lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-Ovid2_S2_R1_001_val_1.fq,/lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-Ovid2_S2_R2_001_val_2.fq	1
DKO_Ovid	/lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-Ovid3_S3_R1_001_val_1.fq,/lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-Ovid3_S3_R2_001_val_2.fq	1
DKO_MatureTumor	/lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-MT1_S7_R1_001_val_1.fq,/lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-MT1_S7_R2_001_val_2.fq	2
DKO_MatureTumor	/lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-MT2_S8_R1_001_val_1.fq,/lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-MT2_S8_R2_001_val_2.fq	2
DKO_MatureTumor	/lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-MT3_S9_R1_001_val_1.fq,/lustre/work/epigenomics/klinkebiel/parallel/LIONS/data/GSF1734-D1-MT3_S9_R2_001_val_2.fq	2

**Comment by biscuit13161** [comment]
Hi Dave,

I had that come up too... I think that's an issue with the file paths ...

For me, it was because the files were gzipped but the input.list defined
non-gzipped files, so LIONS couldn/t find them

@Artem Babaian <ababaian@bccrc.ca> do you think it's worth adding a file
check to allow this gzip/non-gzip difference without erroring?

thanks,
Richard

**Comment by dklinkebiel** [comment]
How could I correct for this issue with current LIONS. Would unzipping files work. Thanks
Dave

**Comment by biscuit13161** [comment]
Hi Dave,

Sorry for the late reply, I'm on holiday at the moment.

It's just a mismatch between input.list and the file names. As the files
are already gzipped, i'd just modify the input.list to match. Especially as
one of the first steps is to gzip the files if they aren't!

Best,
Richard

**Comment by dklinkebiel** [comment]
Hi Richard,

Seem to have run into another error. Attached are the error and out logs. Thanks

Dave
[LIONS_OUT.txt](https://github.com/ababaian/LIONS/files/3527389/LIONS_OUT.txt)
[LIONS_ERR.txt](https://github.com/ababaian/LIONS/files/3527390/LIONS_ERR.txt)

**Comment by dklinkebiel** [comment]
Hi Richard,

Have you had a chance to look at my last LIONS error. Thanks

Dave

**Comment by biscuit13161** [comment]
Hi Dave,

Apologies for not getting back to you earlier, I've been away and I
realised that I'd been testing against the wrong species reference.

I'm running some tests at the moment and I'll get back to you soon.

Best,
Richard

**Comment by dklinkebiel** [comment]
Thanks !!

**Comment by biscuit13161** [comment]
Hi Dave,

Apologies for how long this has taken, but I think I've sorted it now...

It appears one of the steps got confused when there's more than one entry with the same starting coordinates in the Repeat Masker DB. I've amended and committed the script, but let me know if you're still having issues.

Best,
Richard

**Comment by dklinkebiel** [comment]
Hi Richard,

The folders are not downloading complete.

Dave

**Comment by biscuit13161** [comment]
Hi Dave,

I'm afraid I've re-downloaded the folders (using git clone) on a couple of
different computers without issue...🤔
How are you getting the files? ... git clone? ... or downloading the zip
file? ... or Github Desktop?

Artem,

Are you aware of any issues with this?

Best,
Richard

**Comment by dklinkebiel** [comment]
Hi Richard,

Do the attached error and out logs suggest that LIONS completed. Thanks
Now to determine what the out put means. Any clues about that.

Dave
[LIONS_ERR.txt](https://github.com/ababaian/LIONS/files/3799732/LIONS_ERR.txt)
[LIONS_OUT.txt](https://github.com/ababaian/LIONS/files/3799733/LIONS_OUT.txt)

**Comment by biscuit13161** [comment]
Hi Dave,

That's pretty much what I had expected ... unless Artem sees something I
don't.

Artem, do you have any comments about interpreting the output?

Best,
Richard

**Comment by ababaian** [comment]
This looks like it completed? I don't see anything either that's out of the ordinary.

**Comment by dklinkebiel** [comment]
Hi Artem,

I was looking at the LIONS output and in the <project> *.lions output there is a category “Contribution An estimate of the promoter contribution of this Repeat TSS to the ex-
pression of gene in total. Calculated with ExonMax and UpExonMax.” Is this value the percent of contribution? For example a value of 0.5 would be 0.05 percent of total or is it 50 percent of total. Thanks

Dave

**Comment by ababaian** [comment]
0.5 would be 50% of total expression. Keep in mind this is an estimate but it's pretty spot on a lot of the time.

**Comment by dklinkebiel** [comment]
How do you account  for value such as 1.89 ? Thanks

Dave

**Comment by ababaian** [comment]
The expression of the TE portion is higher then the gene with which it fuses.
