### ISSUE TITLE
Fail to parse input.list

### ISSUE THREAD

**Issue by Alex-Nesta** [ababaian/LIONS#15]
Hi again,

I am unable to get lions to accept my input.list file. I have tried manually entering the tabs and entering in three separate columns in excel. I get the same error each time.

Here is my input.list file:

Here is the error:
```
awk: /projects/beck-lab/alex/bin/LIONS/scripts/Initialize/input.list.awk:16:   a[s][t] = $0; 
awk: /projects/beck-lab/alex/bin/LIONS/scripts/Initialize/input.list.awk:16:       ^ syntax error
awk: /projects/beck-lab/alex/bin/LIONS/scripts/Initialize/input.list.awk:21:     for ( j in a[i]) {
awk: /projects/beck-lab/alex/bin/LIONS/scripts/Initialize/input.list.awk:21:                 ^ syntax error
awk: /projects/beck-lab/alex/bin/LIONS/scripts/Initialize/input.list.awk:22:       print a[i][j]
awk: /projects/beck-lab/alex/bin/LIONS/scripts/Initialize/input.list.awk:22:                 ^ syntax error
```

This happens even using the default input.list file included with LIONS.
```
gm12878	/LIONS-data/GM12878.rep1.R1.fastq.gz,/LIONS-data/GM12878.rep1.R2.fastq.gz	1
k562	/LIONS-data/K562.rep1.R1.fastq.gz,/LIONS-data/K562.rep1.R2.fastq.gz	2
```

Not sure if it is due to a recent change in the code? I checked out the latest revision yesterday and installed on top of my existing one by copy and paste overwriting. Maybe that was a bad idea. I can try a clean install tomorrow.

EDIT: Same issue on fresh install. I commented on the commit where the input.list parsing last changed. Hoping you have time to look into this soon. For now I will try to check out an older commit.

**Comment by biscuit13161** [comment]
Hi Alex,

Can you let me know what version of awk and what operating system you are using?

Can you send me the input.list.awk and input.list files you're using?


Best,
Richard

**Comment by ababaian** [comment]
Having a bit of trouble reproducing as well, can you provide more info Alex?

**Comment by Alex-Nesta** [comment]
Hey guys,

Thanks for looking into this.
I am running LIONS on my compute cluster, so I am not using Docker.

Here is my awk and linux version:

```

(base) [nestaa@helix LIONS]$ awk --version
GNU Awk 3.1.7
Copyright (C) 1989, 1991-2009 Free Software Foundation.

(base) [nestaa@helix LIONS]$ uname -r
2.6.32-754.3.5.el6.x86_64

```

Sorry, I had to compress the input.list file to keep it totally untouched and still able to upload. It's literally the git cloned version though. I did NOTHING to it.

[input.list.zip](https://github.com/ababaian/LIONS/files/3617800/input.list.zip)

**Comment by biscuit13161** [comment]
Hi Alex,

I need the input.list.awk file that's causing you issues as the latest version is syntactically correct for awk/gawk

thanks,
Richard

**Comment by biscuit13161** [comment]
Hi Alex,

fyi, the reason the earlier version is working is that it doesn't correct for replicates, and as such it doesn't use awk.

best,
Richard

**Comment by biscuit13161** [comment]
Hi Alex,

The latest version works for me in gawk (I'm using both v4.0.1 and v5.0.1) ... Awk (on the mac) does seem to be an issue, but the attached file should correct that. Please try this file ([input.list.awk.gz](https://github.com/ababaian/LIONS/files/3619457/input.list.awk.gz)) with the latest version and let me know how it goes.

FYI, the reason the earlier version is working is that it doesn't use awk ... the input.list.awk script was added to correct a bug relating to working with replicates.

thanks,
Richard

**Comment by Alex-Nesta** [comment]
Hi Richard,

I just tested with the new input.list.awk file you provided. It looks like it is working! Thank you!

For your reference, here is the old input.list.awk that did not work.
[input.list.awk.bak.zip](https://github.com/ababaian/LIONS/files/3621764/input.list.awk.bak.zip)
