### ISSUE TITLE
coverage threshold  for TE 

### ISSUE THREAD

**Issue by whiteorchid** [ababaian/LIONS#21]
By the results, in the RepeatMaxCoverage column, some results items are 0. So does this means that LIONS  will report all the TEs without a cutoff?

Thanks a lot!

**Comment by ababaian** [comment]
This is correct, all TE-exon interactions are reported the idea being that you as the researcher will set the cut-offs that you deem appropriate. As a general rule I go with at least 10-read support for a particular interaction.

It's an arbitrary heuristic, there are sensitivity-specificity trade-offs and 10 reads is is very close to the optimal (max AUC) distance when I did the benchmarking. There is no "correct" answer in this regard.
