### ISSUE TITLE
Could not find Bowtie2 index file presist

### ISSUE THREAD

**Issue by WalterHK** [ababaian/LIONS#22]
Hello,

         I have encountered a closed issue in which the solution is to use the most update LIONS and all fastq should be compressed. However, I still have the same problem. Followings are the code for executing lions_opt.sh

./lions_opt.sh \
-P /home/mytools/LIONS/WTRNA_para/WTRNA.ctrl \
-b /home/mytools/LIONS \
-p WTRNAseq \
-i /home/mytools/LIONS/WTRNA_para/input.list 
--callsettings oncoexaptation 
--index /home/mytools/LIONS/resources/hg19/genome/hg19 
--geneset /home/mytools/LIONS/resources/hg19/annotation/refSeq_hg19.ucsc 
--repeatmasker /homemytools/LIONS/resources/hg19/repeat/rm_hg19.ucsc 
--systemctrl /homemytools/LIONS/controls/system.sysctrl 
--bowtie bowtie2 
--alignbypass 1 
--threads 40
  
   Following are the error codes:
Checking for Bowtie
Bowtie verison: 2.2.6.0
Checking for Bowtie index file (genome)..
Error: Could not find Bowtie 2 index file (bowtie2.*.bt2l)
du: cannot access _accepted_hits.bam_: No such file or directory
/home/mytools/LIONS/scripts/eastLion.sh: line 194: [: -ge unary operator expected 
Alignment probably didnt work

        Since I using hg19 which size is less than 4G, bt2l should not be generated.

        Thank you for your help.

Best,
Walter

**Comment by ababaian** [comment]
Sorry I will get to this later in the evening when the tyke is asleep. or did you resolve this?

**Comment by WalterHK** [comment]
Thank you for your instant response, the problem is mine since I declare something wrong in the parameter file.

**Comment by ababaian** [comment]
I apologize in advance this isn't the most user-friendly software. I was a PhD student learning software development on the fly.

**Comment by WalterHK** [comment]
May I ask if the program takes 6 hours to complete alignments, how long the post alignment work needs?

**Comment by ababaian** [comment]
About the same time, the python scripts need to go through read by read to calculate statistics.
