### ISSUE TITLE
Can I use existing alignment results from STAR as input for LIONS?

### ISSUE THREAD

**Issue by Lynuxoo** [ababaian/LIONS#27]
Hello,

I noticed that LIONS uses TopHat for alignment. Now that I have the alignment results from STAR, is there a way to provide my existing alignment results as input to LIONS?

Thanks in advance for your help!

**Comment by ababaian** [comment]
Yes, in the parameter file there is a an `ALIGNMENT BYPASS` flag which you can set to use bam files as they are provided.

See: https://github.com/ababaian/LIONS/blob/595bc6fc2a8f6d2f31ce121d63a9d3a7a812af6e/controls/parameter.ctrl#L55

Cheers
