### ISSUE TITLE
incorrect syntax in Dockerfile?

### ISSUE THREAD

**Issue by benbfly** [ababaian/LIONS#4]
The following line was added to the last check-in of Dockerfile (line 87):
mv /LIONS-master /LIONS

But it looks like Docker is trying to interpret it as a Docker command since it is not concatenated to the RUN command using &&.  I am getting a parse error.  Am I doing something wrong or was this check in never tested?

Thanks,
Ben.

**Comment by ababaian** [comment]
Hey Ben,

You're correct, it's a bug. Thanks for the heads-up.

Artem
